import type { ElementInspection } from '../../shared/types';

/** A realistic button inspection — computed styles a browser would report. */
export function buttonInspection(overrides: Partial<ElementInspection> = {}): ElementInspection {
  return {
    ref: { selector: '.btn-primary', xpath: '/html/body/button', domPath: [1, 2] },
    tagName: 'BUTTON',
    visible: true,
    rect: { x: 10, y: 20, width: 120, height: 40, top: 20, left: 10, right: 130, bottom: 60 },
    text: 'Get started',
    layout: {
      display: 'inline-flex',
      position: 'relative',
      width: 'auto',
      height: 'auto',
      minWidth: '0px',
      maxWidth: 'none',
      minHeight: '0px',
      maxHeight: 'none',
      boxSizing: 'border-box',
      margin: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
      padding: { top: '8px', right: '16px', bottom: '8px', left: '16px' },
      gap: '8px',
      rowGap: '8px',
      columnGap: '8px',
      flexDirection: 'row',
      flexWrap: 'nowrap',
      justifyContent: 'center',
      alignItems: 'center',
      alignContent: 'normal',
      flexBasis: 'auto',
      flexGrow: '0',
      flexShrink: '1',
      order: '0',
      gridTemplateColumns: 'none',
      gridTemplateRows: 'none',
      gridTemplateAreas: 'none',
      gridAutoFlow: 'row',
      justifyItems: 'normal',
      overflowX: 'visible',
      overflowY: 'visible',
      zIndex: 'auto',
      float: 'none',
      clear: 'none',
    },
    appearance: {
      color: '#ffffff',
      backgroundColor: '#635bff',
      borderWidth: '0px',
      borderStyle: 'none',
      borderColor: 'rgb(0, 0, 0)',
      borderRadius: '8px',
      boxShadow: 'none',
      opacity: '1',
      filter: 'none',
      backdropFilter: 'none',
      mixBlendMode: 'normal',
      clipPath: 'none',
      maskImage: 'none',
      isolation: 'auto',
    },
    typography: {
      fontFamily: 'Inter, sans-serif',
      fontSize: '14px',
      fontWeight: '600',
      fontStyle: 'normal',
      lineHeight: '20px',
      letterSpacing: 'normal',
      wordSpacing: '0px',
      textTransform: 'none',
      textDecoration: 'none',
      textAlign: 'center',
      whiteSpace: 'normal',
      textOverflow: 'clip',
      fontVariantNumeric: 'normal',
    },
    advanced: {
      transform: 'none',
      transformOrigin: '50% 50% 0px',
      transition: 'all 0.15s ease 0s',
      animation: 'none',
      perspective: 'none',
      backfaceVisibility: 'visible',
      contain: 'none',
      contentVisibility: 'visible',
      containerType: 'normal',
      containerName: 'none',
      aspectRatio: 'auto',
      willChange: 'auto',
      cursor: 'pointer',
      userSelect: 'auto',
    },
    boxModel: {
      margin: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
      padding: { top: '8px', right: '16px', bottom: '8px', left: '16px' },
      borderWidth: { top: '0px', right: '0px', bottom: '0px', left: '0px' },
      borderStyle: { top: 'none', right: 'none', bottom: 'none', left: 'none' },
      borderColor: {
        top: 'rgb(0, 0, 0)',
        right: 'rgb(0, 0, 0)',
        bottom: 'rgb(0, 0, 0)',
        left: 'rgb(0, 0, 0)',
      },
      contentRect: {
        x: 11,
        y: 21,
        width: 118,
        height: 38,
        top: 21,
        left: 11,
        right: 129,
        bottom: 59,
      },
    },
    html: {
      tagName: 'BUTTON',
      id: undefined,
      classes: ['btn-primary'],
      attributes: { type: 'submit' },
      aria: {},
      data: {},
      outerHTML: '<button type="submit" class="btn-primary">Get started</button>',
      outerHTMLTruncated: false,
      innerHTML: 'Get started',
      innerHTMLTruncated: false,
      textContent: 'Get started',
      selector: '.btn-primary',
      xpath: '/html/body/button',
      domPath: [1, 2],
    },
    traces: [],
    variables: [],
    variablesTruncated: false,
    inherited: [],
    matchedRules: [],
    matchedRulesTruncated: false,
    blockedStylesheets: [],
    declarationCount: 0,
    ...overrides,
  };
}
